services:

  db:
    image: postgres:15
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .

    command: >
      sh -c "
        ./wait-for-it.sh db:5432 --timeout=60 --
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app

    ports:
      - "80:8000"

    depends_on:
      - db

    env_file:
      - .env


volumes:
  postgres_data: