name: Django Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d

      - name: Run tests
        run: docker compose exec web sh -c "flake8 . && pytest"
